### ISSUE TITLE
请问，这个代码是基于rocketmq-cpp-client哪个版本？

### ISSUE THREAD

**Issue by HUHANK** [yuntong613/RocketMQ#1]

**Comment by yuntong613** [comment]
基于master分支

**Comment by HUHANK** [comment]
![image](https://github.com/yuntong613/RocketMQ/assets/9984283/de22dbec-2bb6-474d-8fbb-4cad2796dd0f)
hello，我用你的工程编译，有上面截图的这些报错，请问你有遇到过吗？

**Comment by HUHANK** [comment]
我用的是vs2019的编译器

**Comment by yuntong613** [comment]
需要使用vcpkg安装boost依赖库，看一下vcpkg的使用说明 @HUHANK

**Comment by HUHANK** [comment]
安装了，我是使用vcpkg安装的

**Comment by HUHANK** [comment]
![image](https://github.com/yuntong613/RocketMQ/assets/9984283/835e2373-2bd1-4f5f-8571-7128973cbcb0)

**Comment by yuntong613** [comment]
运行命令 vcpkg integrate install 集成到VS中，之后重启VS，重新加载项目

**Comment by HUHANK** [comment]
嗯，是按照你的方式弄了，还是一样的

**Comment by yuntong613** [comment]
boost-smart-ptr 看下vcpkg有自动安装这个依赖吗，没有安装一下

**Comment by yuntong613** [comment]
vcpkg 安装一下 这几个库 boost-log boost-iostreams boost-locale boost-lambda boost-foreach

**Comment by HUHANK** [comment]
![image](https://github.com/yuntong613/RocketMQ/assets/9984283/2605cb1c-3751-48cc-a831-8388d6de36c2)
vcpkg integrate install 安装完成之后也执行了这条语句，然后关闭VS，重启VS，打开项目，重新编译，还是报一样的错误
![image](https://github.com/yuntong613/RocketMQ/assets/9984283/1b5aa22a-05a8-4e82-a11e-fffc312342f3)

**Comment by yuntong613** [comment]
编译工程时候是否是x64？

**Comment by HUHANK** [comment]
是的打开默认的，X64 Debug

**Comment by HUHANK** [comment]
![image](https://github.com/yuntong613/RocketMQ/assets/9984283/1b5b3a7f-c87d-43ad-870b-9a1257267127)
还有个问题，工程目录少了这个log目录，我这是从rocketmq-cpp-client工程拷贝过去的

**Comment by yuntong613** [comment]
工程属性里，有个vcpkg菜单是否选选为Debug
![image](https://github.com/yuntong613/RocketMQ/assets/20533580/36d91bdf-92d9-45e7-b80e-c3edd5f54608)

**Comment by HUHANK** [comment]
![image](https://github.com/yuntong613/RocketMQ/assets/9984283/cd0a36d8-2689-425e-8412-dd9a3bd0e2bb)
跟你的一样的

**Comment by yuntong613** [comment]
我尝试了，没有问题，其他文件是不是用官方的覆盖了？原版的头文件顺序有些问题

**Comment by HUHANK** [comment]
我在报错的文件添加#include <boost/weak_ptr.hpp> 这个未定义的报错没了

**Comment by HUHANK** [comment]
![image](https://github.com/yuntong613/RocketMQ/assets/9984283/56c2d5be-4bd1-4dd3-9734-404e62493de5)
这个连接错误，是boost版本不对吗？

**Comment by HUHANK** [comment]
![image](https://github.com/yuntong613/RocketMQ/assets/9984283/04a6f13e-7146-4d82-bce5-3bbb0fa6fb68)
这是我这边boost的版本

**Comment by yuntong613** [comment]
用我代码里的Logging文件，重新拉一下

**Comment by HUHANK** [comment]
![企业微信截图_17180940946384](https://github.com/yuntong613/RocketMQ/assets/9984283/ccaa5520-9ac6-4172-b92b-46e7469d9688)
Debug X64我编译成功了， 我再试试Release的动态库，和静态库

**Comment by HUHANK** [comment]
非常感谢，动态库可以用了，编译的静态库，可以编译成功，但是使用时找不到定义，这个我后面再看看；
